# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:35
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adulto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnis', models.IntegerField(default=0)),
                ('cedula', models.IntegerField(default=0)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('gen', models.CharField(max_length=1)),
                ('f_nac', models.DateField(default=datetime.datetime.now)),
                ('f_promesa', models.DateField(blank=True, default=datetime.datetime.now)),
                ('unidad', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('n_capacit', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=30)),
                ('distrito', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=70)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Joven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnis', models.IntegerField(default=0)),
                ('cedula', models.IntegerField(default=0)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('gen', models.CharField(max_length=1)),
                ('f_nac', models.DateField(default=datetime.datetime.now)),
                ('f_promesa', models.DateField(blank=True, default=datetime.datetime.now)),
                ('unidad', models.CharField(max_length=30)),
                ('adelanto', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=30)),
                ('distrito', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=70)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="El telefono debe estar en formato: '+999999999'.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.AddField(
            model_name='joven',
            name='celular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='j_celular', to='maximas.Telefono'),
        ),
        migrations.AddField(
            model_name='joven',
            name='tel_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='j_te_local', to='maximas.Telefono'),
        ),
        migrations.AddField(
            model_name='adulto',
            name='celular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_celular', to='maximas.Telefono'),
        ),
        migrations.AddField(
            model_name='adulto',
            name='tel_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_te_local', to='maximas.Telefono'),
        ),
    ]
