# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joven',
            name='adelanto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='joven',
            name='celular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='j_celular', to='maximas.Telefono'),
        ),
        migrations.AlterField(
            model_name='joven',
            name='direccion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='joven',
            name='distrito',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='joven',
            name='grupo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='joven',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='joven',
            name='region',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='joven',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='joven',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='joven',
            name='tel_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='j_te_local', to='maximas.Telefono'),
        ),
        migrations.AlterField(
            model_name='joven',
            name='unidad',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
