# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0002_auto_20170527_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joven',
            name='celular',
            field=models.CharField(blank=True, default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joven',
            name='f_nac',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='joven',
            name='f_promesa',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='joven',
            name='tel_local',
            field=models.CharField(blank=True, default=0, max_length=30),
            preserve_default=False,
        ),
    ]
