# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0003_auto_20170527_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adulto',
            name='dnis',
        ),
        migrations.RemoveField(
            model_name='joven',
            name='dnis',
        ),
    ]
