# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0008_certificado_evento_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='dnis',
            field=models.IntegerField(default=0),
        ),
    ]
