# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0009_participante_dnis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='nombre',
            new_name='codigo',
        ),
    ]
