# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0010_auto_20170529_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('unidad', models.CharField(choices=[('MM', 'MM'), ('MF', 'MF'), ('TM', 'TM'), ('TF', 'TF'), ('CM', 'CM'), ('CF', 'CF')], max_length=2)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maximas.Certificado')),
            ],
        ),
    ]
