# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0011_cip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cip',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maximas.Certificado'),
        ),
    ]
