# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0014_auto_20170531_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cip',
            name='unidad',
            field=models.CharField(choices=[('M', 'M'), ('T', 'T'), ('C', 'C'), ('G', 'G')], max_length=1),
        ),
    ]
