# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0015_auto_20170531_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='nombre',
            new_name='primer_apellido',
        ),
        migrations.AddField(
            model_name='participante',
            name='primer_nombre',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participante',
            name='segundo_apellido',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participante',
            name='segundo_nombre',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
