# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 03:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0016_auto_20170531_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condecoraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnis', models.IntegerField(default=0)),
                ('condecoracion', models.CharField(choices=[('NPB', 'Nudo de Perseverancia en Bronce'), ('NPP', 'Nudo de Perseverancia en Plata'), ('NPO', 'Nudo de Perseverancia en Oro'), ('BESP', 'Barra de Espiritud Scout en Plata'), ('BESO', 'Barra de Espiritud Scout en Oro'), ('BV', 'Barra Vinotinto'), ('OM1', 'Orden al Merito Primera Clase'), ('OM2', 'Orden al Segunda Clase'), ('OSJ', 'Orden de San Jorge')], max_length=4)),
                ('fecha_entrega', models.DateField(default=datetime.datetime.now)),
                ('numero', models.IntegerField(default=0)),
            ],
        ),
    ]
