# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0020_participantecip_participantecursos_participanteprogramasmundiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantecip',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='participantecip',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='participantecip',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='participantecip',
            name='segundo_nombre',
        ),
        migrations.RemoveField(
            model_name='participantecursos',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='participantecursos',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='participantecursos',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='participantecursos',
            name='segundo_nombre',
        ),
        migrations.RemoveField(
            model_name='participanteprogramasmundiales',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='participanteprogramasmundiales',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='participanteprogramasmundiales',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='participanteprogramasmundiales',
            name='segundo_nombre',
        ),
    ]
