# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 03:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0023_participanteprogramasmundiales_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnis', models.IntegerField(default=0)),
                ('tipo', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=0)),
                ('fecha_entrega', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='participanteprogramasmundiales',
            name='numero',
            field=models.CharField(max_length=5),
        ),
    ]
