# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0025_adelanto'),
    ]

    operations = [
        migrations.AddField(
            model_name='adelanto',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 6, 7, 19, 7, 23, 130900)),
        ),
    ]
