# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0027_auto_20170607_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adelanto',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
