# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0028_auto_20170607_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanteprogramasmundiales',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
