# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximas', '0029_auto_20170608_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='adelanto',
            field=models.CharField(choices=[('LO', 'Lobato'), ('FR', 'Huella Fresca'), ('AL', 'Huella Alerta'), ('AG', 'Huella Agil'), ('LI', 'Huella Libre'), ('LS', 'Lobo Saltarin'), ('NO', 'Novicio'), ('AV', 'Aventurero'), ('EX', 'Explorador'), ('PI', 'Pionero'), ('SB', 'Scout de Bolivar'), ('NV', 'Novato'), ('PR', 'Precursor'), ('EP', 'Expedicionario'), ('DE', 'Descubridor'), ('FU', 'Fundador'), ('RC', 'Rover Ciudadano')], max_length=2),
        ),
    ]
